# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LLhS6Q6_yf_lLuw938JDTbQR8A6MenBb
"""

!pip install fastapi uvicorn pydantic pyngrok nest-asyncio

# 1. تثبيت المكتبات
!pip install fastapi uvicorn pyngrok nest-asyncio pydantic

import uvicorn
from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel
import nest_asyncio
from pyngrok import ngrok
import threading
import time
import sqlite3 # استدعاء مكتبة الـ SQL الخاصة بالبايثون

app = FastAPI()
app.add_middleware(CORSMiddleware, allow_origins=["*"], allow_methods=["*"], allow_headers=["*"])

# --- إعداد قاعدة البيانات SQLite ---
def init_db():
    conn = sqlite3.connect('incidents.db', check_same_thread=False)
    cursor = conn.cursor()
    cursor.execute('''
        CREATE TABLE IF NOT EXISTS incidents (
            id TEXT,
            type TEXT,
            source TEXT,
            lat REAL,
            lng REAL,
            timestamp DATETIME DEFAULT CURRENT_TIMESTAMP
        )
    ''')
    conn.commit()
    return conn

db_conn = init_db()

# تعديل الموديل عشان يقبل الداتا حتى لو ناقصة
class Incident(BaseModel):
    id: float
    type: str
    lat: float
    lng: float
    confidence: float = 0.0  # لو مبعتيش confidence هيحط 0
    source: str = "Unknown"  # لو مبعتيش source هيحط Unknown

last_incident = {
    "id": 1,
    "type": "safe",
    "lat": 30.0444,
    "lng": 31.2357,
    "confidence": 1,
    "source": "Initial"
}

@app.post("/new-incident")
async def create_incident(incident: Incident):
    global last_incident
    last_incident = incident.dict()

    # حفظ في الداتا بيز
    cursor = db_conn.cursor()
    cursor.execute('''
        INSERT INTO incidents (id, type, source, lat, lng)
        VALUES (?, ?, ?, ?, ?)
    ''', (str(incident.id), incident.type, incident.source, incident.lat, incident.lng))
    db_conn.commit()

    print(f"✅ Received from ReqBin: {incident.type} | Source: {incident.source}")
    return {"status": "success"}

@app.get("/get-last-incident")
async def get_incident():
    return last_incident

# 🔥 تشغيل السيرفر
def run_server():
    nest_asyncio.apply()
    uvicorn.run(app, host="0.0.0.0", port=8000)

# قفل أي Tunnels قديمة عشان ميعملش Error
ngrok.kill()

threading.Thread(target=run_server).start()
time.sleep(2)

# 🔥 ربط ngrok
ngrok.set_auth_token("3C1gnROX4gamx9kQdHuHTxv9P0L_6Q9QK9SiV5YoNR451wYpt")
public_url = ngrok.connect(8000)

print(f"\n✅ SERVER IS LIVE!")
print(f"🔗 API ENDPOINT (For Camera): {public_url.public_url}/new-incident")
print(f"🔗 DASHBOARD URL: {public_url.public_url}/get-last-incident\n")

from google.colab import drive
drive.mount('/content/drive')

import sqlite3
conn = sqlite3.connect('incidents.db')
cursor = conn.cursor()

# إضافة صف يدوي للتجربة
cursor.execute('''
    INSERT INTO incidents (id, type, source, lat, lng)
    VALUES (?, ?, ?, ?, ?)
''', ("999", "test_fire", "Manual_Test", 31.0, 31.2))

conn.commit()
conn.close()
print("✅ تم إضافة صف تجريبي يدوي بنجاح!")

import sqlite3
import pandas as pd

conn = sqlite3.connect('incidents.db')
df = pd.read_sql_query("SELECT * FROM incidents ORDER BY timestamp DESC", conn)
conn.close()
df # هيعرض لك أحدث البيانات فوق

!npm install sqlite3